hash-format = "sha256"

[[files]]
file = "config/energizedpower/common.conf"
hash = "82b138b6eef0a3e9f9444db0df10bf9b294cabbbc36469264febe8b57173a8a7"

[[files]]
file = "config/modmenu.json"
hash = "1c35cd3fc90d49ec0b369924ad85905be05d8fde2499be7f769f6847f008c0c8"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "1fc1e482945dff68e6aab34b22d61d054a6177869408ed4af3fef6117a33faab"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "659f7b849f370718cc5216c3de0fdc4863391f9889d00ebd4ccef8274ee7026d"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
hash = "492b3c59c096542b5ca733e5a19f66c870deaa6a98a409ee8497fe50d39ac7db"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "f34fa12fe7701cf0776fef1a1f1e2e3c7227f53302b3d87b7ff307f0446a68d2"
metafile = true

[[files]]
file = "mods/bluemap.pw.toml"
hash = "24737d4ec343e590df0fb597f52bd792557300b659b828492bfd51d63c1fe52d"
metafile = true

[[files]]
file = "mods/bluemapvisabilitytoggle.pw.toml"
hash = "d3a303055be459f77bd8f9b55a8921db51508d01ea756ae4ece66e002a1bc71d"
metafile = true

[[files]]
file = "mods/chisel-reborn.pw.toml"
hash = "cf8b8ee9b5c3d3dbe28c2b6a46f500af3765d4fbbd4146b7c766850809a7c4f8"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "64badefe03082699f587274a31d1f0793583a4d88aac8ea2226162f80783fb52"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "717d8ac591dba59be4767a179e1359747561e54ccfcac42161fd6bf54339a78b"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "3d24d58b2caf4fd73d76b2d734a1d06490994d5d38177376e6f5d8d9f8fb87e0"
metafile = true

[[files]]
file = "mods/compact-help-command.pw.toml"
hash = "83e6eab6cf3a22c763dbb077b8ee8d41eef62a2f9530080fd626aed61f402581"
metafile = true

[[files]]
file = "mods/cryonicconfig.pw.toml"
hash = "8691ea7075e76c17a637af2fc542b1b17db618b1c6d5a525b8e2fdec39e6fb5a"
metafile = true

[[files]]
file = "mods/energized-power.pw.toml"
hash = "66a8ea046add95e54d70b0b7cdf88d16386f3d0d2af94e36290ffcb5469685cd"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "cbda4f1881cfb9f054395a3db225df4202d1f2e7bd0ed27d803b837fcf728621"
metafile = true

[[files]]
file = "mods/fuji.pw.toml"
hash = "2f54900f945ec85e7647cb04f052daab7bb63ffbac9310b176e95d999a1be90e"
metafile = true

[[files]]
file = "mods/inventory-essentials.pw.toml"
hash = "0d0f7c8bec24c453c31d15c05418f15ba48b4576a327510c315eae81fa5de9b0"
metafile = true

[[files]]
file = "mods/inventory-management.pw.toml"
hash = "b50651c2c054ff67985150b5a80198fda6606545f7d68e92548d1a7fea4c0914"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "bdca3c9a098de3c08f996b214cf10ece27351f5f7871c30ff826a2f404daba33"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "1031fc249666fd4c19555037df86d9aa3c3c7378733b594cf4207b3e606e8e55"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "84957275e9dc6f07f4244ce3303536e3d73b0e72eb1696ccd024168a52c29c98"
metafile = true

[[files]]
file = "mods/luckperms.pw.toml"
hash = "78eb7a4883effdbab78ff513fba684e62783bad2ef54b1aeef0fe584af490c67"
metafile = true

[[files]]
file = "mods/luckpermsplaceholderapi.pw.toml"
hash = "69a9db16719867b5aa41056c79ef42b51eceaf7fd2adb63f7384866ed91c0caa"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
hash = "d9999ebfa59a092f278d6b03abffe3ff7f9d039ae6680d4d0e2f777e8664ea99"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "012898817d8b30563579014b87476c865e0e5a4ebb267f44a0fdc2af3bc6dac3"
metafile = true

[[files]]
file = "mods/macaws-fences-and-walls.pw.toml"
hash = "120c3328d887e2961a288dd78aad828b515262ee2c994f463f16abec919c11b7"
metafile = true

[[files]]
file = "mods/macaws-lights-and-lamps.pw.toml"
hash = "b30c3b7e15aa8c78fda4cfeac5484ea603934afc88579627fed23dfc4a68dbdf"
metafile = true

[[files]]
file = "mods/macaws-paths-and-pavings.pw.toml"
hash = "ce1b6ef9f766026fbaf1cf5e23ff5f80d16b9ffab806f3cbc9ad3d824e03b20b"
metafile = true

[[files]]
file = "mods/macaws-roofs.pw.toml"
hash = "788ecd207be847c554cc9df527c506875869a7fcf3ac78c42fa5fba49c428b19"
metafile = true

[[files]]
file = "mods/macaws-stairs.pw.toml"
hash = "717dadb9d7b3ba4955a4c81630fc584f1584b3a4104f92144e2a83eda0c61783"
metafile = true

[[files]]
file = "mods/macaws-trapdoors.pw.toml"
hash = "e033f0e4ccdf7afd9ae2791b5559d30487b271d690c37698bc512f11ff07687a"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
hash = "c1166163c44561f41e925654c4f018a60a97173077c88c86a8944a4fae503225"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "5dd45d5fd5e1ae2bd521b93a70b83c69b57ada18f424c6562d8c6ea9980cfb3e"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
hash = "c21e5c7c86e20d26b9936224db71c94558049000dbf2481f3f1649a62b41f2a1"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "e674752dd4dd07c33d9b94f6e19c15ef893c356c3c5ed77aeaf35cf6d2325130"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "42a73228a2e7ddd0a2ebba1e2a03dec5dbf4605854ec89c05f7e1374baffeae5"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "279ea1bb4b776be9176fe34416e2132e37abfce4483def54177091cc0f2faade"
metafile = true

[[files]]
file = "mods/styled-chat.pw.toml"
hash = "b14b41445fb21e4e2fc0c3ec1dd289afead8e75abce76fa6e0c2256585627514"
metafile = true

[[files]]
file = "mods/styledplayerlist.pw.toml"
hash = "fcc4f588960a66fb5182ea2ce53d9b184d43c1511aa3dfc12af240b74d00812a"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "dba564c761870715c46e527e182ece9d0c50ae96c8c4e3af3f2b567e2816565d"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
hash = "3834da8c79b0b87de1f8a25e3c55ee3e007df2f47d19ac9f2126524893f1032f"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "993390d4661a77aa83c8416f75addfccaf7cee0a7a7311a21742b2036700b5ac"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "53c8bc02c9b10610c43fc29127039036217e33a95ab2ea2d6ac291987266ef89"
metafile = true
