name = "Kreativ Knoten"
author = "Lurky"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "961e2ce1a1ad1b9c31fc13aaf3800d7a475701145557556c182b7f7e59272f67"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
