name = "Kreativ Knoten"
author = "Lurky"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17f0a59fb197a92733912db310987f083d2532d364f0e142176525ad887eb171"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
