name = "Kreativ Knoten"
author = "Lurky"
version = "0.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "280a0db64049a1472f59a90bbcea1a183406b78e88c3d5ba548e7fd417cde552"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
